// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyDt9GqPmKQpTkOE6p7-J0zhgh93HkAGA',
    appId: '1:503527786987:android:f8e0157ba147798bdf71ae',
    messagingSenderId: '503527786987',
    projectId: 'changathiapp-dev',
    storageBucket: 'changathiapp-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH9rrMWBirFHYV7dRtnFvTrXX0tXP5bqY',
    appId: '1:584798238803:ios:5ebeac229583a1239faea6',
    messagingSenderId: '584798238803',
    projectId: 'nizhal-app-prod',
    storageBucket: 'nizhal-app-prod.firebasestorage.app',
    iosBundleId: 'com.vibetalks.customer',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPipI8FGaH73x9IeXaZMLwwvor6ypFEWc',
    appId: '1:584798238803:web:84ff7f3d8584fd779faea6',
    messagingSenderId: '584798238803',
    projectId: 'nizhal-app-prod',
    authDomain: 'nizhal-app-prod.firebaseapp.com',
    storageBucket: 'nizhal-app-prod.firebasestorage.app',
    measurementId: 'G-WG336BW060',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH9rrMWBirFHYV7dRtnFvTrXX0tXP5bqY',
    appId: '1:584798238803:ios:d42e4c56d79e0a949faea6',
    messagingSenderId: '584798238803',
    projectId: 'nizhal-app-prod',
    storageBucket: 'nizhal-app-prod.firebasestorage.app',
    iosBundleId: 'com.example.vibeTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPipI8FGaH73x9IeXaZMLwwvor6ypFEWc',
    appId: '1:584798238803:web:7825b028405f30309faea6',
    messagingSenderId: '584798238803',
    projectId: 'nizhal-app-prod',
    authDomain: 'nizhal-app-prod.firebaseapp.com',
    storageBucket: 'nizhal-app-prod.firebasestorage.app',
    measurementId: 'G-8ST258W7V1',
  );
}
